git push origin main[Kbash scripts/script[K[K[K[Kript_normal_dif_test.sh 
[?2004l[2025-03-27 03:03:06,445] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 03:03:09,382] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-03-27 03:03:09,383] [INFO] [runner.py:607:main] cmd = /hpc2hdd/home/yli045/.conda/envs/ywj/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None main.py --image_size 8 --batch_size 1 --num_epochs 20 --timesteps 100 --lr 2e-4 --time_emb_dim 32 --mu1 4 --sigma1 1 --num1 900 --mu2 10 --sigma2 4 --num2 100 --samples_dir ./samples --checkpoints_dir ./checkpoints --fp16 --mode train --model_path  --num_images 1000 --simulation_distribution normal --use_different_noise --use_moe --num_experts 2 --moe_hidden_dim 2 --moe_tau 0.1
[2025-03-27 03:03:11,572] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 03:03:13,061] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-03-27 03:03:13,061] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-03-27 03:03:13,061] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-03-27 03:03:13,061] [INFO] [launch.py:164:main] dist_world_size=1
[2025-03-27 03:03:13,061] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-03-27 03:03:13,062] [INFO] [launch.py:256:main] process 362516 spawned with command: ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1']
[2025-03-27 03:03:16,891] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 03:03:23,062] [INFO] [logging.py:128:log_dist] [Rank -1] DeepSpeed info: version=0.16.4, git-hash=unknown, git-branch=unknown
[2025-03-27 03:03:23,062] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-03-27 03:03:23,062] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-03-27 03:03:23,066] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/main.py", line 9, in <module>
[rank0]:     train_deepspeed(cfg)
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/train.py", line 100, in train_deepspeed
[rank0]:     model_engine, optimizer, train_loader, _ = deepspeed.initialize(
[rank0]:                                                ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 273, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1237, in _configure_distributed_model
[rank0]:     self.module.to(self.device)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1343, in to
[rank0]:     return self._apply(convert)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   [Previous line repeated 1 more time]
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 991, in _apply
[rank0]:     self._buffers[key] = fn(buf)
[rank0]:                          ^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1329, in convert
[rank0]:     return t.to(
[rank0]:            ^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W327 03:03:25.128338231 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-03-27 03:03:26,064] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 362516
[2025-03-27 03:03:26,064] [ERROR] [launch.py:325:sigkill_handler] ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1'] exits with return code = 1
[?2004h(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ export CUDA_VISIBLE_DEVICES=""
[?2004l[?2004h(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ export CUDA_VISIBLE_DEVICES=""bash scripts/script_normal_dif_test.sh 
[?2004l[2025-03-27 03:09:49,175] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-03-27 03:09:49,207] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-03-27 03:09:51,843] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-03-27 03:09:51,844] [INFO] [runner.py:607:main] cmd = /hpc2hdd/home/yli045/.conda/envs/ywj/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None main.py --image_size 8 --batch_size 1 --num_epochs 20 --timesteps 100 --lr 2e-4 --time_emb_dim 32 --mu1 4 --sigma1 1 --num1 900 --mu2 10 --sigma2 4 --num2 100 --samples_dir ./samples --checkpoints_dir ./checkpoints --fp16 --mode train --model_path  --num_images 1000 --simulation_distribution normal --use_different_noise --use_moe --num_experts 2 --moe_hidden_dim 2 --moe_tau 0.1
[2025-03-27 03:09:53,851] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-03-27 03:09:53,859] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-03-27 03:09:55,015] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-03-27 03:09:55,015] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-03-27 03:09:55,015] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-03-27 03:09:55,015] [INFO] [launch.py:164:main] dist_world_size=1
[2025-03-27 03:09:55,015] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-03-27 03:09:55,016] [INFO] [launch.py:256:main] process 363891 spawned with command: ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1']
[2025-03-27 03:09:59,251] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 03:10:05,465] [INFO] [logging.py:128:log_dist] [Rank -1] DeepSpeed info: version=0.16.4, git-hash=unknown, git-branch=unknown
[2025-03-27 03:10:05,466] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-03-27 03:10:05,466] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-03-27 03:10:05,470] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/main.py", line 9, in <module>
[rank0]:     train_deepspeed(cfg)
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/train.py", line 100, in train_deepspeed
[rank0]:     model_engine, optimizer, train_loader, _ = deepspeed.initialize(
[rank0]:                                                ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 273, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1237, in _configure_distributed_model
[rank0]:     self.module.to(self.device)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1343, in to
[rank0]:     return self._apply(convert)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   [Previous line repeated 1 more time]
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 991, in _apply
[rank0]:     self._buffers[key] = fn(buf)
[rank0]:                          ^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1329, in convert
[rank0]:     return t.to(
[rank0]:            ^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W327 03:10:06.099891591 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-03-27 03:10:07,018] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 363891
[2025-03-27 03:10:07,019] [ERROR] [launch.py:325:sigkill_handler] ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1'] exits with return code = 1
[?2004h(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ [K(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ bash scripts/script_normal_dif_test.sh 
[?2004l[2025-03-27 03:11:45,320] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-03-27 03:11:45,328] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-03-27 03:11:47,018] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-03-27 03:11:47,019] [INFO] [runner.py:607:main] cmd = /hpc2hdd/home/yli045/.conda/envs/ywj/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None main.py --image_size 8 --batch_size 1 --num_epochs 20 --timesteps 100 --lr 2e-4 --time_emb_dim 32 --mu1 4 --sigma1 1 --num1 900 --mu2 10 --sigma2 4 --num2 100 --samples_dir ./samples --checkpoints_dir ./checkpoints --fp16 --mode train --model_path  --num_images 1000 --simulation_distribution normal --use_different_noise --use_moe --num_experts 2 --moe_hidden_dim 2 --moe_tau 0.1
[2025-03-27 03:11:49,115] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-03-27 03:11:49,123] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-03-27 03:11:50,319] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-03-27 03:11:50,320] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-03-27 03:11:50,320] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-03-27 03:11:50,320] [INFO] [launch.py:164:main] dist_world_size=1
[2025-03-27 03:11:50,320] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-03-27 03:11:50,427] [INFO] [launch.py:256:main] process 364479 spawned with command: ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1']
[2025-03-27 03:11:54,445] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 03:11:59,268] [INFO] [logging.py:128:log_dist] [Rank -1] DeepSpeed info: version=0.16.4, git-hash=unknown, git-branch=unknown
[2025-03-27 03:11:59,268] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-03-27 03:11:59,268] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-03-27 03:11:59,271] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/main.py", line 9, in <module>
[rank0]:     train_deepspeed(cfg)
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/train.py", line 103, in train_deepspeed
[rank0]:     model_engine, optimizer, train_loader, _ = deepspeed.initialize(
[rank0]:                                                ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 273, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1237, in _configure_distributed_model
[rank0]:     self.module.to(self.device)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1343, in to
[rank0]:     return self._apply(convert)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   [Previous line repeated 1 more time]
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 991, in _apply
[rank0]:     self._buffers[key] = fn(buf)
[rank0]:                          ^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1329, in convert
[rank0]:     return t.to(
[rank0]:            ^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W327 03:11:59.817470348 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-03-27 03:12:01,439] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 364479
[2025-03-27 03:12:01,440] [ERROR] [launch.py:325:sigkill_handler] ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1'] exits with return code = 1
[?2004h(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ bash scripts/script_normal_dif_test.sh 
[?2004l[2025-03-27 03:13:52,754] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-03-27 03:13:52,762] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-03-27 03:13:54,638] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-03-27 03:13:54,639] [INFO] [runner.py:607:main] cmd = /hpc2hdd/home/yli045/.conda/envs/ywj/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None main.py --image_size 8 --batch_size 1 --num_epochs 20 --timesteps 100 --lr 2e-4 --time_emb_dim 32 --mu1 4 --sigma1 1 --num1 900 --mu2 10 --sigma2 4 --num2 100 --samples_dir ./samples --checkpoints_dir ./checkpoints --fp16 --mode train --model_path  --num_images 1000 --simulation_distribution normal --use_different_noise --use_moe --num_experts 2 --moe_hidden_dim 2 --moe_tau 0.1
[2025-03-27 03:13:56,788] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-03-27 03:13:56,796] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-03-27 03:13:57,940] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-03-27 03:13:57,941] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-03-27 03:13:57,941] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-03-27 03:13:57,941] [INFO] [launch.py:164:main] dist_world_size=1
[2025-03-27 03:13:57,941] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-03-27 03:13:57,952] [INFO] [launch.py:256:main] process 365036 spawned with command: ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1']
[2025-03-27 03:14:01,805] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 03:14:06,673] [INFO] [logging.py:128:log_dist] [Rank -1] DeepSpeed info: version=0.16.4, git-hash=unknown, git-branch=unknown
[2025-03-27 03:14:06,673] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-03-27 03:14:06,674] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-03-27 03:14:06,678] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/main.py", line 9, in <module>
[rank0]:     train_deepspeed(cfg)
[rank0]:   File "/hpc2hdd/home/yli045/diffusion_noise_agent/train.py", line 103, in train_deepspeed
[rank0]:     model_engine, optimizer, train_loader, _ = deepspeed.initialize(
[rank0]:                                                ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 273, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1237, in _configure_distributed_model
[rank0]:     self.module.to(self.device)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1343, in to
[rank0]:     return self._apply(convert)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
[rank0]:     module._apply(fn)
[rank0]:   [Previous line repeated 1 more time]
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 991, in _apply
[rank0]:     self._buffers[key] = fn(buf)
[rank0]:                          ^^^^^^^
[rank0]:   File "/hpc2hdd/home/yli045/.conda/envs/ywj/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1329, in convert
[rank0]:     return t.to(
[rank0]:            ^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W327 03:14:07.456922016 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-03-27 03:14:07,953] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 365036
[2025-03-27 03:14:07,954] [ERROR] [launch.py:325:sigkill_handler] ['/hpc2hdd/home/yli045/.conda/envs/ywj/bin/python', '-u', 'main.py', '--local_rank=0', '--image_size', '8', '--batch_size', '1', '--num_epochs', '20', '--timesteps', '100', '--lr', '2e-4', '--time_emb_dim', '32', '--mu1', '4', '--sigma1', '1', '--num1', '900', '--mu2', '10', '--sigma2', '4', '--num2', '100', '--samples_dir', './samples', '--checkpoints_dir', './checkpoints', '--fp16', '--mode', 'train', '--model_path', '', '--num_images', '1000', '--simulation_distribution', 'normal', '--use_different_noise', '--use_moe', '--num_experts', '2', '--moe_hidden_dim', '2', '--moe_tau', '0.1'] exits with return code = 1
[?2004h(ywj) yli045@7b9adf13479a:~/diffusion_noise_agent$ 